### ISSUE TITLE
addToClipboard support

### ISSUE THREAD

**Issue by guliashvili** [GoogleChrome/chrome-extensions-samples#1055]
https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/functional-samples/cookbook.offscreen-clipboard-write 

> In the future, the Chrome team is planning to add clipboard support directly to extension service workers. As such, this recipe is written to make it as easy as possible to replace addToClipboard()'s offscreen document-based implementation with one that directly uses the appropriate clipboard API.

As Chrome is pushing forward the deprecation of manifest V2, I'm wondering, is `addToClipboard` going to be supported soon?

**Comment by patrickkettner** [comment]
Hi @guliashvili!
This repo is intended for the samples themselves, rather than platform updates. crbug.com would be the place to track status of features.

That being said, MV3 extensions can use the code from the code sample. It is not impacted by the MV2 timeline. The feature is still planned on being added, but there is no more detailed plans to share as of now.
