### ISSUE TITLE
continuous recording sample - allow user to select media stream tab or window ?

### ISSUE THREAD

**Issue by giannik** [GoogleChrome/chrome-extensions-samples#1081]
Is it not possible to allow user the define the media stream  from the select tab , window dialog and pass that stream for continuous recording . the following example only works for current tab and user cannot select the media stream . am i missing something ?

https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/functional-samples/sample.tabcapture-recorder

**Comment by oliverdunk** [comment]
Hi @giannik! The `tabCapture` sample is using the [`chrome.tabCapture`](https://developer.chrome.com/docs/extensions/reference/api/tabCapture) API which allows you to capture without a dialog, with the tradeoff it must be triggered from a user gesture and only for the current tab.

If you'd like to have more control, you can use the web platform APIs: https://developer.chrome.com/docs/extensions/how-to/web-platform/screen-capture

I'm going to close this since this issue tracker is for the samples specifically, but feel free to reach out with additional questions in our mailing list: https://groups.google.com/a/chromium.org/g/chromium-extensions
