### ISSUE TITLE
Network preview tab override

### ISSUE THREAD

**Issue by bbert** [GoogleChrome/chrome-extensions-samples#1103]
Is there a way to override default network "Preview" in order to customize the response body preview?
As a complement the idea could be to transform the response body into JSON and then reuse the embedded JSON previewer.

**Comment by oliverdunk** [comment]
At the moment, other than a few integration points (panes in the elements panel, for example), extensions can only add entirely new UI. There isn't a way to extend existing UI like the network response and you would need to add a new network panel. I'm going to close this for now since this repository is for questions about the samples, but if you'd like to discuss more, feel free to post in our mailing list: https://groups.google.com/a/chromium.org/g/chromium-extensions

**Comment by bbert** [comment]
@oliverdunk thanks for your feedback, I will do post my question in the mailing list
