### ISSUE TITLE
sidePanel has minimum width of 495 pixels. too large.

### ISSUE THREAD

**Issue by audioscavenger** [GoogleChrome/chrome-extensions-samples#1156]
⚠️ If you have general Chrome Extensions questions, consider posting to the [Chromium Extensions Group](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-extensions) or [Stack Overflow](https://stackoverflow.com/questions/tagged/google-chrome-extension).

**Describe the bug**
sidePanel has minimum width of 475 pixels. too large.

**To Reproduce**
1. enable side panel

**Expected behavior**
we should be able to resize it down to a useful set minimum of 200px, scrollbar included

**Screenshots**
![image](https://github.com/GoogleChrome/chrome-extensions-samples/assets/3853962/5be74fae-d543-4760-ac67-bc4e4fd64d33)

**Notes**
please please please at least let us know which file to modify to change the minimum width

**Comment by patrickkettner** [comment]
Hi Eric!
This repo is meant for code samples, rather than product feedback. For that, you would want to use crbug.com/new

However, this is an existing conversation the team is already working on. Unfortunately there isn't a way to change that today, but I am hopeful there will be options in the near future.
