### ISSUE TITLE
Bug: This extension may soon no longer be supported

### ISSUE THREAD

**Issue by probonopd** [GoogleChrome/chrome-extensions-samples#1256]
**Describe the bug**

One of the most popular extensions, [uBlock Origin](https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm), triggers a strange message (screenshot below), saying "This extension may soon no longer be supported".

Apparently this has to do with the the phasing out of "MV2 extensions", whatever that is.

__So please do NOT phase out "MV2 extensions" because they are essential to an advertising-free web.__

**To Reproduce**

https://github.com/uBlockOrigin/uBlock-issues/issues/3309

**Expected behavior**

uBlock Origin works like it always has.

**Screenshots**

![image](https://github.com/user-attachments/assets/09a5c9cc-de0d-4e2f-8369-222dc37e2a1a)

**Notes**

* https://github.com/uBlockOrigin/uBlock-issues/issues/3309
* [More information](https://www.youtube.com/watch?v=1vuJ05k5FxM)

**Comment by oliverdunk** [comment]
Hi @probonopd - you can learn more about Manifest V3 and our plans for the MV2 deprecation here: https://developer.chrome.com/blog/resuming-the-transition-to-mv3. If you haven't found it already, there are some alternatives you can consider migrating to, like [uBlock Origin Lite](https://chromewebstore.google.com/detail/ublock-origin-lite/ddkjiahejlhfcafbddmgiahcphecmpfh) published by the same author.

I'm going to close this issue since this issue tracker is for our code samples, but I hope this helps.

**Comment by probonopd** [comment]
The point is, where at Google can we (the users) make our voices heard in a productive way that we*d appreciate MV2 not being deprecated? So that Product Management can overthink their decisions.

**Comment by oliverdunk** [comment]
We've been working with developers on this change for several years now, and we've received a lot of feedback already. We still think this is the best direction so it's very unlikely we will make significant changes to the rollout plan at this point. Unfortunately, I don't have a specific channel I can point you towards but we'll keep looking at the various developer support channels we have to identify gaps in capabilities and add new features to add to the platform.
