### ISSUE TITLE
How to add a command that opens the popup via keyboard shortcut?

### ISSUE THREAD

**Issue by Fannon** [GoogleChrome/chrome-extensions-samples#619]
Hi,

maybe I've overseen something obvious, but I have a hard time finding out how to add a command that toggles the popup of my extension (I want to trigger it on a keyboard shortcut).

There are many chrome extensions which do this, but all I found are still using manifest version 2.

Previously, this seems to have been done automatically though the `_execute_browser_action` command: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#special_shortcuts 

Maybe this could also be added to a simpler example, that introduces how to create the popup?

Best regards,

**Comment by Fannon** [comment]
Ok, I could get it work. My problems were the following:

* The extension needs to be reloaded AND chrome to be restarted before some keyboard shortcuts actually become active
* The new "magic" command for this seems to be `_execute_action`

```json
"commands": {
    "_execute_action": {
      "suggested_key": {
        "default": "Ctrl+Period",
        "mac": "Command+Period"
      }
    }
  },
```

**Comment by sobujbd** [comment]
How to retrieve the `_execute_action` key to show it in the option page. Since we can retrieve `_execute_browser_action` key.

**Comment by patrickkettner** [comment]
Hi @Fannon! [Here is a sample](https://play.web-extensions.dev/#s=N4IgRgTg9g7gzgUwiAXCAwgC2gWwSAGhBwEMA7ASwDME4AXANSTgqjNRAFkGBmQkCmQDGAGwCuAEwQAFKCICeVCiJGoqJEYiJ0EOAA4iSOgJISOZBDAAqJMNJIBzfESUjaqANqgyJPB1KUNPQAdABWcGz8OgAedBzAADpkAATJCSA%2BeOkoaRhQOAEScMlSOFDJALTJJEJ0rCmCAG5QQkb16QRJqemNzO2ouQCMwQAMHV25AdS0dAD6vRAsbNnJPJ0puWA1ANYO0GJkEiuJG90giBCNFEIIszBQENtIK%2BlbQrv7h2Fw6RMAvusznokDgKHAlmQfgMPOkanVejYwB1cnAhBAKHo6mQHOkALqA3Jw-o5E6pM5SdRiERzPRQPRiPQvEC0%2Bl6YKYOg4ES-DYAibpIT5QpQkkTM6zBDRBBCMQ6WZE5YDUlks5wMQOJz0BASWZPeTHMUq3IUkhUuhM9B0CAiADUAFVxqcjelSEILULyBJ7Tyjck-ob-bykn8QADvL58Gg3h8oAcJN8opK4mghNh8ghggqyME2OgRNcnvGSBIJAAZME6CwQAAU1botgAlMkALwAPmSytTuAzqPRmMEDmCkulsoQAGU0Ri6NXlal6xAnHQSfWwKYcivghQJHynVQDkIcoKyJW6BO%2B3QAGL7gmpEgLuA5DwAcizT-x-wbAG5g1%2Bkkk98IdRsMkR4nmeU5XsI1aZAgTbKhoSDTgABukAAkwAwf6IDJMOMo6BISG-mQgZJAA9KRyRWJgYIgRoIjRskADqxilqWyQAHIAPJWMkYAILRKjaskVAPLkEpSnhtxZjyXbpsEgoFJ6cA5mQ6Ael8xZlhWCBVrWCmFE2bYdhMR4RG4wQiFADjVkhamKYcuTofpnpYQJbgEURfxfqGBDhn4aAsgy7Kcqo2hJhwAA8ACEAAinHoFYACa0gAKLJByXKtkkEWYIMrbUVFUURaRuWtqGuJ-EAA) that opens a popup when you click Ctrl/CMD-U. You can modify the keys you wish to bind to within the `manifest.json`.

@sobujbd I am terribly sorry, but I am not but I do not understand the question. Given the extreme amount of time that has passed since you asked the question, I am going to close this out. Please either open a new issue or stack overflow for any further assistance.

thanks!
