### ISSUE TITLE
Is it possible to use jQuery to operate on DOM in MV3?

### ISSUE THREAD

**Issue by nanhuajiaren** [GoogleChrome/chrome-extensions-samples#706]
I take [page redder](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/functional-samples/sample.page-redder) as an example. The given example uses `document.body.style = ...` with `chrome.scripting.executeScript()`, now is it possible to use jQuery (`$("body").css()`) instead? I tried but `$` was `undefined`.

**Comment by kellycode** [comment]
I think page_redder is meant to be an example of how the background script, a service worker, is used for event handling and they're fairly inflexible.  Using it to modify page content isn't it's purpose.  Content scripts, on the other hand, can easily load and use external scripts like jquery, css, etc., and are appropriate for page content changes.

**Comment by guest271314** [comment]
You can check if jQuery is defined in the document, then inject jQuery into the document if not already defined.

**Comment by kellycode** [comment]
The content_scripts is far more useful than the background service_worker for simple page mods and easily allows jquery. 

"content_scripts": [
        {
            "matches": ["<all_urls>"],
            "run_at": "document_idle",
            "css": ["content.css"],
            "js": ["jquery-3.5.1.min.js", "content.js"]
        }
    ],

**Comment by Ambushfall** [comment]
Yes, you can use Jquery, it's bloating, but yeah, possible.

I would highly advise to understand how content scripts work and try fiddling with them a bit, you'll get it working!

Make sure to always include jquery before your content script.

(There's also a way of injecting a script into a page, but that's a different story)

**Comment by PabloBorda** [comment]
it used to be so easy in mv2 but anyway people love complications

**Comment by good-guy1218** [comment]
It is possible to use jquery to operate DOM.
Sometimes maybe you need to inject cdn link

**Comment by patrickkettner** [comment]
Like @Ambushfall said, jQuery isn't great for browser extensions because it is meant to smooth over issues in older browsers. Since extensions don't need to work with old browsers, it's better to use plain js.

But, if you really want to use jQuery, you can! You just have to add it yourself. `$` is `undefined` because it's not part of the browser -  you have to give it to the extension. How you do this depends on where you're using it.

In Manifest v3 extensions, you have to bundle any js you want to use with the extension. If you wanted to use this in a `content_script`, then you can do with need to use the [`web_accessible_resources`](https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/) field within [`content_scripts`](https://developer.chrome.com/docs/extensions/mv3/content_scripts/) of your manifest.json file. This lets you add a bundled script to a `<script>` tag on the page in a page that is compliant with mv3

If you had jQuery saved in your extension as `lib/jQuery.js`, then adding them to the manifest looks like this

```json
// manifest.json
...
"content_scripts": [
    {
        "matches": ["https://MetroCalculator.com/*"],
        "js": ["content_script.js"],
        "web_accessible_resources": ["lib/jQuery.js"]
    }
]
...
```

You can then load the library like so

```js
const jQueryURL = chrome.runtime.getURL('lib/library.js');
const scriptElement = document.createElement('script');
scriptElement.setAttribute('src', jQueryURL);
document.head.appendChild(scriptElement);
```

After you do this, $ will work as expected.



Separately, I absolutely understand the sentiment behind comments like  @PabloBorda's - I know it can be irritating, but there's a reason it's like this. The extra steps are important because they help browsers make sure that extensions that claim to do something actually do it and can't secretly add bad things later. This way, they can't be compromised later on.
