### ISSUE TITLE
Sample: Assign arbitrary Window, Worker, SharedWorker, Worklet as a Client

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/chrome-extensions-samples#781]
Sample: Assign an arbitrary `Window`, `Worker`, `SharedWorker`, `Worklet` as a `Client` of MV3 `ServiceWorker`.

This will eliminate the current need for multiple workarounds to establish communication between the `ServiceWorker` and arbitrary Web page for the ability to _transfer_ Transferable Objects, etc. from the `ServiceWorker` to the arbitrary Web page.

**Comment by dotproto** [comment]
Closing as this appears to be an extension platform feature request rather than an extension sample one.

To more directly address the request, this feels like something Chrome is very unlikely to do for two primary reasons. First, this type of use is well outside the intended design and utility of service workers and their clients. Second, this use case is would be more effectively addressed another way, like moving the extension platform from a custom message system to the web platform messaging model.

Please open an issue on crbug.com. Ideally, this issue report should focus on the problem you're encountering rather than a specific solution.
