### ISSUE TITLE
Impossible to write to or read from clipboard in offscreen document

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/chrome-extensions-samples#795]
**Describe the bug**
Impossible to read from or write to clipboard in an offscreen document - even when `clipboard_read` and `clipboard_write` permissions are `"granted"`.

**To Reproduce**

Navigate to Details of the extension, then Site settings, and set Clipboard permission to Allow.

```
await chrome.offscreen.createDocument({
  url: 'offscreen.html',
  justification: 'ignored',
  reasons: ['CLIPBOARD'],
});
```

In the script loaded by the offscreen document 

```
(async () => {
  try {
    let clipboard_permissions = (
      await navigator.permissions.requestAll([
        { name: 'clipboard-read' },
        { name: 'clipboard-write' },
      ])
    ).map(({ state }) => state);
    if (clipboard_permissions.every((state) => state === 'granted')) {
      await navigator.clipboard.writeText(location.href);
      console.log(await navigator.clipboard.readText(location.href));
    } else {
      console.log(clipboard_permissions);
    }
  } catch (e) {
    console.error(e.message);
  }
})();
```

```
Document is not focused.
```

**Expected behavior**
Read and write to clipboard in an offscreen document.

**Screenshots**

**Notes**
I don't think it is possible to gain focus on an offscreen document. At least not using any of the approaches I have tried, including `focus()` and calling the clipboard read and write methods in an `NotificationEvent` handler.

Nonetheless `CLIPBOARD` is listed as a "reason" in offscreen documentation https://developer.chrome.com/docs/extensions/reference/offscreen/, though appears to be useless at this point.

**Comment by dotproto** [comment]
As you indicated, the web Clipboard API can only be used in the currently focused page. This is limitation of the Clipboard API was intentional for the web platform, but may be something we can change for extensions platform. I just opened [crbug.com/1404835](https://crbug.com/1404835) to track this feature request. That issue also contains link sot several other related issues, the most notable of which is probably [1160302](https://crbug.com/1160302), which is a request to expose the clipboard API to extension service workers.

More germain to your specific request, it _is_ possible to interact with the system clipboard using `document.execComand('copy')`. PR #797 (opened earlier today) is a cookbook example showing how to use it in an offscreen document.

**Comment by guest271314** [comment]
The idea is to utilize Async Clipboard API to write a `File` to the clipboard with `ClipboardItem` and get the contents of clipboard items on arbitrary Web pages that can read from the clipboard. The examples does not achieve that.

**Comment by dotproto** [comment]
@guest271314, you're welcome to edit the original issue report on this issue to focus specifically on copying a file and reopen the issue. At the moment I'm thinking a good general purpose example might be to copy an image (PNG or JPEG), but I'm curious if you have something else in mind.
